### PR TITLE
completely changed the UI and the CSS

### PR DESCRIPTION
**Pull request by trahulprabhu38**
made several changes to the UI , hope u like it ;) .

Please accept the PR

### CODE REVIEW

**Comment by harshit1142** [comment]
@T-Rahul-prabhu-38 does not look good.

**Comment by trahulprabhu38** [comment]
what colour do u prefer? dark theme?

**Comment by harshit1142** [comment]
@T-Rahul-prabhu-38 someone is working on it. I will suggest you the changes you can make. Wait for a few hours, I will assign you the task for sure.

**Comment by harshit1142** [comment]
@T-Rahul-prabhu-38 sync your repo and discard the changes you have made. Fix the height of the navbar and also change background color of footer .

**Pull request closed without merging**
